### ISSUE TITLE
broadlinkbridge.service failure

### ISSUE THREAD

**Issue by Julianex22** [fbacker/broadlink-mqtt-bridge#12]
Hello fbacker.
Broadlinkbridge.service does not work anymore, next is the result of to review its status, could you please give some guidance about how to repair it. I tried of reinstall but it does not work.

`sudo systemctl status broadlinkbridge.service
` broadlinkbridge.service - Broadlink MQTT Bridge
   Loaded: loaded (/etc/systemd/system/broadlinkbridge.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2019-01-30 12:46:03 -05; 9s ago
  Process: 2150 ExecStart=/usr/bin/node index.js (code=exited, status=1/FAILURE)
 Main PID: 2150 (code=exited, status=1/FAILURE)

Jan 30 12:46:03 openHABianPi systemd[1]: broadlinkbridge.service: Main process exited, code=exited, status=1/FAILURE
Jan 30 12:46:03 openHABianPi systemd[1]: broadlinkbridge.service: Unit entered failed state.
Jan 30 12:46:03 openHABianPi systemd[1]: broadlinkbridge.service: Failed with result 'exit-code'.
`

**Comment by Julianex22** [comment]
Hello fbacker.

when I run index.js directly this is the result.

`env { LC_ALL: 'en_US.UTF-8',
  LS_COLORS:
   'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:',
  LANG: 'en_US.UTF-8',
  NO_AT_BRIDGE: '1',
  LC_CTYPE: 'en_US.UTF-8',
  TERM: 'xterm',
  LANGUAGE: 'en_US.UTF-8',
  PATH:
   '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
  MAIL: '/var/mail/root',
  LOGNAME: 'root',
  USER: 'root',
  USERNAME: 'root',
  HOME: '/root',
  SHELL: '/bin/bash',
  SUDO_COMMAND: '/usr/bin/node index.js',
  SUDO_USER: 'openhabian',
  SUDO_UID: '1000',
  SUDO_GID: '1000' }
commandsPath /srv/openhab2-conf/broadlink-mqtt-bridge/commands
2019-02-01 19:46:02 [info]:     Starting Broadlink MQTT NodeJS Application
2019-02-01 19:46:02 [info]:     MQTT Options {
  "host": "127.0.0.1",
  "port": 1883,
  "protocol": "mqtt",
  "subscribeBasePath": "broadlink",
  "username": "openhabian",
  "password": "7121799422"
}
Discover device 5
2019-02-01 19:46:03 [info]:     GUI Web listen on port 3000
2019-02-01 19:46:03 [info]:     MQTT Connected {
  "cmd": "connack",
  "retain": false,
  "qos": 0,
  "dup": false,
  "length": 2,
  "topic": null,
  "payload": null,
  "sessionPresent": false,
  "returnCode": 0
}
2019-02-01 19:46:03 [debug]:    MQTT Message {
  "topic": "broadlink/switch/comedor/on",
  "msg": "play-34ea346ff7ac"
}
2019-02-01 19:46:03 [debug]:    prepareAction {
  "action": "play-34ea346ff7ac",
  "topic": "broadlink/switch/comedor/on",
  "origin": "mqtt"
}
2019-02-01 19:46:03 [debug]:    MQTT Message {
  "topic": "broadlink/switch/comedor/off",
  "msg": "play-34ea346ff7ac"
}
2019-02-01 19:46:03 [debug]:    prepareAction {
  "action": "play-34ea346ff7ac",
  "topic": "broadlink/switch/comedor/off",
  "origin": "mqtt"
}
2019-02-01 19:46:03 [debug]:    MQTT Message {
  "topic": "broadlink/switch/cocina/dos/on",
  "msg": "play-34ea346ff7ac"
}
2019-02-01 19:46:03 [debug]:    prepareAction {
  "action": "play-34ea346ff7ac",
  "topic": "broadlink/switch/cocina/dos/on",
  "origin": "mqtt"
}
2019-02-01 19:46:03 [debug]:    MQTT Message {
  "topic": "broadlink/switch/cocina/dos/off",
  "msg": "play-34ea346ff7ac"
}
2019-02-01 19:46:03 [debug]:    prepareAction {
  "action": "play-34ea346ff7ac",
  "topic": "broadlink/switch/cocina/dos/off",
  "origin": "mqtt"
}
mqtt failed No devices
mqtt failed No devices
mqtt failed No devices
mqtt failed No devices
events.js:174
      throw er; // Unhandled 'error' event
      ^

SyntaxError: Unexpected token
`
Please give me a light about How I could repair this problem.

Thanks.

**Comment by fbacker** [comment]
It might take up a couple of seconds before callback with device is triggered. A crash might be happening because mqtt events are running before a device is found. Because I can't see a device is found.

Will make some tests.

**Comment by fbacker** [comment]
Please make an upgrade and see if it works. Else run ```node index.js``` and paste the output again. Thanks @Julianex22

**Comment by Julianex22** [comment]
Hello Fbacker.

Thanks for you respond, I will make your indications and will post the result, today I am at work, tomorrow I will send my results.

Thanks again.

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by Julianex22** [comment]
Fbacker your solution works fine, after upgrade the service have been quite stable, I really appreciate your willing.
Thanks.
