### ISSUE TITLE
New RM mini 3 Version with id 0x27de

### ISSUE THREAD

**Issue by gituser2a** [fbacker/broadlink-mqtt-bridge#14]
Hi, I just bought a new RM mini 3. It was not discovered by broadlinkbridge:

[Info] We've discovered an unknown Broadlink device. This likely won't cause any issues.

Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "27de". The device is connected to your network with the IP address "192.168.2.112".

I added it to broadlinkjs-rm/index.js line 11 as
rmDeviceTypes[parseInt(0x27de, 16)] = 'Broadlink RM Mini 3 v2';

After this it was discovered. Please add the new device type in the repo.

**Comment by fbacker** [comment]
Good find. The broadlinkjs-rm project seems dead. I'm running a pull from another user. Not been updated for 6 months, even with good pulls. https://github.com/lprhodes/broadlinkjs-rm/pulls
Will look for another package to use.

**Comment by fbacker** [comment]
I've forked the dead repo. So lets try it.
If you update the project your fix should be included.

Please try it out if it works.
