### ISSUE TITLE
Not able to build project with `npm install`

### ISSUE THREAD

**Issue by kevivell** [fbacker/broadlink-mqtt-bridge#17]
This project is of great interest to me however, I'm not able to run npm install on the project.

Node version :- v10.16.0
NPM version :- v6.9.0

Running npm install in verbose mode I get this error :- 

`npm verb stack TypeError: err.code.match is not a function
npm verb stack     at BB.try.catch.err (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/with-tarball-stream.js:110:55)
npm verb stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm verb stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
npm verb stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
npm verb stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
npm verb stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:690:18)
npm verb stack     at _drainQueueStep (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
npm verb stack     at _drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
npm verb stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
npm verb stack     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
npm verb stack     at runCallback (timers.js:794:20)
npm verb stack     at tryOnImmediate (timers.js:752:5)
npm verb stack     at processImmediate [as _immediateCallback] (timers.js:729:5)
`

**Comment by fbacker** [comment]
I can't get the same error. Running npm ```6.7.0```. 
I've upgraded to ```6.9.0``` and it works.

I'm running on a RPI3 with the default openhab installation. Maybe you could try to delete the node_module directory and try again. Else try to use Yarn to install the packages and see if that helps.

Guessing that you are not running on RPI, if you do, please try to auto install script.

**Comment by fbacker** [comment]
I've updated some packages. Did an auto install to upgrade. 
Seems I get the same issue that you got. Either its some security issues buy running install as sudo or a bug a couple of other projects have with this npm version.

I deleted the node_modules directory and run ```npm install``` and now it works.
