### ISSUE TITLE
Multiple devices configuration

### ISSUE THREAD

**Issue by rabihjrab** [fbacker/broadlink-mqtt-bridge#22]
Hello everyone, 
Does anyone know how to use the broadlink-mqtt-bridge V2 with multiple devices?
In the first version, all was working fine.
But, with this new version, I am not able to work with more than 1 device.

Thank you for your help!

**Comment by fbacker** [comment]
Sorry @rabihjrab , it doesn't have this feature yet. Didn't really know how to handle it with a more 'correct' pub/sub syntax. Right now it sends to first connected device, it should send to all.

Any suggestions?

***How about using : as seperator?***
broadlink/fans/livingroom/speed
***could be***
broadlink/fans/livingroom/speed:{device-id}
***as***
broadlink/fans/livingroom/speed:f8d8d6s

**Comment by fbacker** [comment]
@rabihjrab please update and try it.

Added docs here:
https://github.com/fbacker/broadlink-mqtt-bridge/wiki/Multiple-Broadlink-Devices

**Comment by rabihjrab** [comment]
hello @fbacker , i tryed it all, and nothing works.
Thank you for trying to help me.
