### ISSUE TITLE
Recording

### ISSUE THREAD

**Issue by CiZeR41** [fbacker/broadlink-mqtt-bridge#23]
Hi I just got the MQTT Broadlink update to V2, and honstly I preffer the last version the V1, how can I install it back? 
and if it's impossible to get V1 how do I record IR Code on the new V2?

Thank you.

**Comment by fbacker** [comment]
check https://github.com/fbacker/broadlink-mqtt-bridge and the bottom. Should get you back to v1.

For information on how to use v2. Check the wiki https://github.com/fbacker/broadlink-mqtt-bridge/wiki

example for recording ir. use the web gui.

topic: broadlink/mydevice/myfeature
message: on
device: click on the SELECT button by the device list

now you are ready to press the Record IR button and follow the 'helpers' at the top.

**Comment by CiZeR41** [comment]
Hi, sorry for alot of problems, and thank you for helping me.
But I really tried to chaged it back to V1 Because it's very easy and I know how to do it already, can you please explain me how to do it? Right now I've the V2, and I want the V1.
