### ISSUE TITLE
Changing default ports

### ISSUE THREAD

**Issue by gargamelonly** [fbacker/broadlink-mqtt-bridge#24]
I have a system also running Grafana tool which also has a web interface on port 3000.
How can I change the bridge web configuration to use a different port?

**Comment by fbacker** [comment]
Please read the wiki
https://github.com/fbacker/broadlink-mqtt-bridge/wiki/Configuration

create a file ./config/local.json
and put this in. will give you a port of 8080
```js
{
  "gui": {
    "port": 8080
  }
}
```

**Comment by strobel1x** [comment]
The logs are served always at port 3001 (frontail), but the gui is using the config port.

**Comment by fbacker** [comment]
@strobel1x  @gargamelonly  latest version now listens to logs port change as well.
