### ISSUE TITLE
V1 - Not working anymore?

### ISSUE THREAD

**Issue by CiZeR41** [fbacker/broadlink-mqtt-bridge#26]
Hi my friend, I've been using your V1 Git, almost 1 year.
I by mastake moved to V2, And you explained me how to back to V1.

And I sucssed moving to V1 But it's not working, after reboot it's not coming up (even when I tried to start the service manually) , and when it's up I can't find devices, rescan ,record, or playing anything.

What should I do, the V2 Will force me to record all my codes again (over 180 codes).. am I right?

Thank you for your support on your git, really apprciat it.

By the way I am using OpenHab as well.

**Comment by fbacker** [comment]
@CiZeR41 migrate to v2 you do not need to re-record. All old codes will still work.
If you having that many commands I would recommend to backup the 'commands' folder :)

The issue might be because the service script is for v2 or not existing. I might need to update the 'downgrade' help.

Please let me know if this works. 
```bash
sudo cp /srv/openhab2-conf/broadlink-mqtt-bridge/installers/boot/broadlinkbridge.service /etc/systemd/system/
sudo chmod +x /etc/systemd/system/broadlinkbridge.service
sudo systemctl daemon-reload
sudo systemctl restart broadlinkbridge.service
```

Wait a couple of seconds and then try ```sudo systemctl status broadlinkbridge.service``` to view info.
Should say something about
```
● broadlinkbridge.service - Broadlink MQTT Bridge
   Loaded: loaded (/etc/systemd/system/broadlinkbridge.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2019-11-27 18:42:46 CET; 4 days ago
```

**Comment by CiZeR41** [comment]
Yeah, I got this correct last massage:

>    broadlinkbridge.service - Broadlink MQTT Bridge
>    Loaded: loaded (/etc/systemd/system/broadlinkbridge.service; enabled; vendor preset: enabled)
>    Active: active (running) since Sat 2019-12-14 19:36:13 IST; 1min 4s ago"

Now I've the v2, and when I select a folder in the broadlink Ui (:3000), It's working, but when I trying to run a command from the Openhab Basic Ui, this is the errors lines I get:
 
```
2019-12-14 17:47:56 [info]: 	Prepare topic: broadlink/mroom/ac/tvremote/on, message: play-34ea34e3c5f9 

2019-12-14 17:47:56 [error]: 	Failed to find file: /srv/openhab2-conf/broadlink-mqtt-bridge/commands/mroom/ac/tvremote/on/play-34ea34e3c5f9.bin 
```

What should I do to make it work? without re-record all codes, as you said, I dont need to.
Thank you and sorry for the 12 days delay.

**Comment by fbacker** [comment]
No worries. Between kids, work and everything else in life these hobby projects doesn't get much attention from me as they need.

Have you checked https://github.com/fbacker/broadlink-mqtt-bridge/wiki/Multiple-Broadlink-Devices and https://github.com/fbacker/broadlink-mqtt-bridge/wiki/OpenHAB#upgrade-from-v1

Please give an example of your MQTT in openhab using MQTT v2. Looks like the commands don't have a valid string. I'm guessing yours should look something like
```
Type switch : pluggtest1 "Test Plugg 1" [
    commandTopic="broadlink/mroom/ac/tvremote:34ea34e3c5f9",
    stateTopic="broadlink/mroom/ac/tvremote:34ea34e3c5f9"
]
```

**Comment by CiZeR41** [comment]
I really apprciat the help but I really can't understand this, I really weak in Mqtt, and Mqtt Broker, But I tried added the Mqtt Broker to my 'Things', now I need to change all the 'rule' and 'items' as well..

I really prefer to install the V1, my friend still enjoy the V1, what I need to do to get back the V1..
And there is another way to conatct with you more easy? 

Thank you so much for all your time you put it for this !

**Comment by fbacker** [comment]
To use the v1 please look here. Step by step to downgrade. It should work.
https://github.com/fbacker/broadlink-mqtt-bridge#breaking-changes-v1---v2-openhab

**Comment by CiZeR41** [comment]
After doing all those steps it's still running the V2, and not the V1.
The only change after those steps, is a new folder on "Openhabian" of broadlink, and it's not changing anything on the "openhab/conf" (The Original "Broadlink-MQTT-Bridge" location.)

**Comment by CiZeR41** [comment]
Hi!
Update:
I was able to restore backup before update, and now all my codes, and my rules/items are wokring and IR is sending IR Codes, and working, BUT , the all UI not working, I can't record or click andthing on the UI , all the buttoms do nothing (Only the command file in the right side)

**Comment by fbacker** [comment]
I tried it again. All the buttons work for me. It finds device, I can play commands. Are you using chrome? Are you getting anything from the developer console?

**Comment by fbacker** [comment]
stale so closing
