### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by combatistor** [fbacker/broadlink-mqtt-bridge#36]
Is it possible to get the local time in the logs? I get the UTC time but can you adjust according to the location?
One more thing, is it possible to rename the broadlink devices? (Just in the GUI) like broadlink living room, broadlink kitchen and the possibility to sort them by IP address?
Thank you very much !

**Comment by gargamelonly** [comment]
Is it possible to configure the bridge in a default config file to select and use a specific device ID instead of pushing the "select" button after every restart?

**Comment by fbacker** [comment]
Possible in 2.3.0 to add custom names. added device will be auto selected as well. but can't specify the id for that, as they are found they are auto selected.
https://github.com/fbacker/broadlink-mqtt-bridge/wiki/Multiple-Broadlink-Devices#naming-devices

sorting and auto select specific won't be built. When GUI is rewritten in something like reactjs features like this could be created. Now I'm just mashing in jquery stuff.
