### ISSUE TITLE
error to read and put command on device MAC starts with 24:df:A7

### ISSUE THREAD

**Issue by ghost** [fbacker/broadlink-mqtt-bridge#38]
hi,
there are a problem with the device broadlink rm mini with MAC starts with 24:df:A7 and firmware V52071 that no send or read command from broadlink-mqtt-bridge. You have a solution?

**Comment by fbacker** [comment]
Is it a rm4 device maybe?

Found someone that tried to fix for a python https://github.com/mjg59/python-broadlink/pull/317/files but this project is nodejs and using another lib for finding actual devices. I don't have the skills to rewrite the support nor the devices to try it on =/

**Comment by ghost** [comment]
Others for home assistance have resolved with  implement discover() or use gendevice() and the class will be supported automatically, as it uses the same interface. 
Can you help me?

**Comment by ghost** [comment]
Hi isn't a RM4 device but a RM3 with another firmware. The solution on post  https://github.com/mjg59/python-broadlink/pull/317/files not work

**Comment by fbacker** [comment]
I've removed my custom fork from https://github.com/lprhodes/broadlinkjs-rm and now using this npm library. For support on devices they need to be fixed here.

Please post your issue there and when fixed I can make a library upgrade.
