### ISSUE TITLE
[warn]: Failed to find file

### ISSUE THREAD

**Issue by emuell36** [fbacker/broadlink-mqtt-bridge#39]
Hi,

when tring to record my first button i get an "Error: IR timeout" first and when I try to play that button I get this warning [warn]: Failed to find file. 
Any suggestion?

Thank you
Erik

**Comment by fbacker** [comment]
Broadlink device didn't register the ir signal that you wanted to record. That's why no file is created and you can't play it. Try aiming the device you want to record towards the broadlink device, try getting closer or further away until it works.

**Comment by emuell36** [comment]
Hey,

tried it for about an our with different remotes...no chance at all. Is it possible that this a problem due to changed software/hardware? Broadlink Manager reports "Writing compatible device not detected!".

 "os": {
    "platform": "linux",
    "distro": "Raspbian GNU/Linux",
    "release": "10",
    "codename": "buster",
    "kernel": "4.19.97-v7+",
    "arch": "arm",
    "codepage": "UTF-8",
    "logofile": "raspbian",
    "build": "",
    "uefi": false
  },
  "versions": {
    "git": "2.20.1",
    "node": "12.15.0",
    "npm": "6.14.2",
    "v8": "7.7.299.13-node.16"
  },

  "process": {
    "cpu": 0,
    "memory": 3.5
  }`
  "address": "192.168.1.31",
  "family": "IPv4",
  "port": 80,
  "size": 128,
  "macAddress": "24:df:a7:7a:e8:c2",
  "id": "24dfa77ae8c2",
  "model": "Broadlink RM Mini 3 D",
  "type": 24374`
