### ISSUE TITLE
Support for MQTT login

### ISSUE THREAD

**Issue by bench2012** [fbacker/broadlink-mqtt-bridge#42]
Hi,

I am trying to config. this with a MQTT login. The usual mqtt login format is username:password@<MQTT Server>. But this doesn't seems to work. It fail to connect to the MQTT server (both MQTT log and the bridge log confirm this) The bridge is in a docker and so is the MQTT broker. There are other devices connected to the broker and working.

Any idea?

**Comment by daFritz84** [comment]
Have you tried adding `username` and `password` in your local.json?
This project uses [mqtt.js](https://github.com/mqttjs/MQTT.js) and any options in this config file should be directly passed to the library if I'm not mistaken.

e.g.
```
[frigg@frigg config]$ cat local.json
{
  "logging":{
    "level": null
  },
  "mqtt": {
    "host": "frigg.local",
    "port": 1883,
    "protocol": "mqtt",
    "subscribeBasePath": "broadlink/",
    "username": "test",
    "password": "test"
  },
  "queue": {
    "delay": 500
  },
  "webhooks": {
    "scanCompleted": null
  },
  "recording": {
    "timeout": {
      "ir": 15,
      "rf": 15
    },
    "path": null
  },
  "gui": {
    "port": 3000,
    "logs": 3001
  }
}
```

**Comment by bench2012** [comment]
Ay, noted thanks. Will try that.
Thanks again.

**Comment by sujitrp** [comment]
This works perfect
