### ISSUE TITLE
conf.template no such file

### ISSUE THREAD

**Issue by muellererwin** [fbacker/broadlink-mqtt-bridge#43]
> broadlink-mqtt-bridge@1.0.0 start /broadlink-mqtt-bridge
> node -r esm index.js
WARNING: No configurations found in configuration directory:/broadlink-mqtt-bridge/config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
/broadlink-mqtt-bridge/src/config.js:1
TypeError: Cannot read property 'path' of undefined
    at new Config (/broadlink-mqtt-bridge/src/config.js:8:44)
    at Object.<anonymous> (/broadlink-mqtt-bridge/src/config.js:48:9)
    at Generator.next (<anonymous>)
    at Object.<anonymous> (/broadlink-mqtt-bridge/src/logger.js:1)
    at Generator.next (<anonymous>)
    at Object.<anonymous> (/broadlink-mqtt-bridge/index.js:1)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! broadlink-mqtt-bridge@1.0.0 start: `node -r esm index.js`
npm ERR! Exit status 1
npm ERR! Failed at the broadlink-mqtt-bridge@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-17T18_51_33_370Z-debug.log
./docker-entrypoint.sh: line 3: can't open /broadlink-mqtt-bridge/conf.template: no such file

**Comment by muellererwin** [comment]
SOLVED (myself): It was a typo in the commands directory. Error was a little bit misleading.

**Comment by Tediore** [comment]
Care to share what you fixed and where? I'm having the same issue.
