### ISSUE TITLE
RM Mini 3 D will not learn

### ISSUE THREAD

**Issue by rscott1010101** [fbacker/broadlink-mqtt-bridge#45]
Using v.2.3.0 of broadlink-mqtt-bridge with a brand new RM Mini 3 D (type 0x5f36 ). 

Unit is discovered using the app, but will not learn any IR codes. When trying to learn, the LED does not light up.

Had similar issues using python-broadlink, which had to be patched to handle a storageError ( https://github.com/mjg59/python-broadlink/issues/371 )

**Comment by fbacker** [comment]
I've removed my custom fork from https://github.com/lprhodes/broadlinkjs-rm and now using this npm library. For support on devices they need to be fixed here.

Please post your issue there and when fixed I can make a library upgrade.
