### ISSUE TITLE
How to record TC2 Switches

### ISSUE THREAD

**Issue by smartnakh** [fbacker/broadlink-mqtt-bridge#5]

**Comment by fbacker** [comment]
What is TC2 Switches.

**Comment by fbacker** [comment]
Don't know if it's broadlinks own stuff, going 'outside' normal operations, or if it's a RF signal. Redirect the question to the plugin this service is using for support.
https://github.com/lprhodes/broadlinkjs-rm

**Comment by smartnakh** [comment]
2018 Broadlink TC2 EU Standard 433mhz Smart Home RF Touch Light Switches
2Gang 220V Remote Control Wall Touch Switch Panel
 https://s.click.aliexpress.com/e/b1wopu0Z

Le mar. 30 oct. 2018 à 18:15, Fredrick Bäcker <notifications@github.com> a
écrit :

**Comment by fbacker** [comment]
Upgrade to latest and try again. Was some issues with RF recording.
If it doesn't work please post an issue at https://github.com/lprhodes/broadlinkjs-rm

**Comment by smartnakh** [comment]
Any ideas how to trigger the rf from the switch for the recording?

Le mar. 30 oct. 2018 à 21:54, Fredrick Bäcker <notifications@github.com> a
écrit :

**Comment by fbacker** [comment]
No Idea. Fint have a TC2 switch myself.
Must be something about it in the manual.
