### ISSUE TITLE
User and pasword mqtt broker

### ISSUE THREAD

**Issue by Julianex22** [fbacker/broadlink-mqtt-bridge#8]
Hello fbacker let me say you that this is a great proyect, congratulations for it.

My broker Mosquitto have user and pasword, I have created local.json but my web acces trough "myip:3000" has down it.

  /srv/openhab2-conf/broadlink-mqtt-bridge/config/local.json 
{
  "mqtt": {
    "host": "192.168.1.113",
    "port": 1883,
    "protocol": "mqtt",
  "subscribeBasePath": "broadlink"
  "user":"openhabian"
"pwd":"7121799422"
  },
  "recording": {
    "timeout": {
      "ir": 30,
      "rf": 30
    },
    "path": null
  },
  "gui": {
    "port": 3000
  }
}

Thanks for your answer.

**Comment by mtzro2003** [comment]
Just enter your username and password in `config/default.json` like in the below example:
```javascript{
  "mqtt": {
    "host": "127.0.0.1",
    "port": 1883,
    "protocol": "mqtt",
    "subscribeBasePath": "broadlink",
    "username": "broadlink",
    "password": "************"
  },
  "recording": {
    "timeout": {
      "ir": 30,
      "rf": 30
    },
    "path": null
  },
  "gui": {
    "port": 3000
  }
}
```

**Comment by Julianex22** [comment]
Thanks Fbacker for your answer, I really appreciated your work, your solution is fine and works very well.

Thank you so much.
